#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Sync\Command\SyncToGoogleCommand;

$app = new Application();

// register console commands
$app->add(new SyncToGoogleCommand());

$app->run();
