integrations:
    planning_center:
        authentication:
            application_id: 27ecee2e8d5ff42c350aef86ed538b247cb5750f797e58552ec347e15b21e07a
            secret: 81645bcfe13ba48240fad3a88612c2bdfdd7b3d85491ddc47dbcabac736ce7d0
    google:
        authentication:
            installed:
                client_id: "455734393199-9iejl7r0nuf72fl1mqehkgtkh9uon3q1.apps.googleusercontent.com"
                project_id: "Contacts Sync"
                auth_uri: "https://accounts.google.com/o/oauth2/auth"
                token_uri: "https://oauth2.googleapis.com/token"
                auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
                client_secret: "p3rfvjh_dlO1OnapQ6q8ZpL9"
                redirect_uris:
                    - "urn:ietf:wg:oauth:2.0:oob"
                    - "http://localhost"
        domain: provchurch.org

lists:
    - church@provchurch.org
    - men@provchurch.org
    - women@provchurch.org

temp:
    path: tmp
